development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  pool: 10
  database: james
  username: james
  password: password
 
test:
  adapter: postgresql
  encoding: utf8
  host: localhost
  pool: 10
  database: RocketApp_second_test
  username: james
  password: password
 
production:
  adapter: postgresql
  encoding: utf8
  url:  <%= ENV["DATABASE_STATS_URL"] %>
  pool: <%= ENV["DB_POOL"] || 5 %>
